# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401


class Embedder:
    r"""
    Rust BERT embedder for BAAI/bge-small-en-v1.5 (384-dim L2-normalized output).
    
    Constructed eagerly: weights load from the HF cache in `__new__`. If
    `IAI_MCP_EMBED_OFFLINE=1` is set, construction fails loudly when any
    required file is missing rather than triggering a silent network download.
    
    The `module` attribute attributes this class to `iai_mcp_native.embed`
    in the generated `.pyi` stub — pyo3-stub-gen derives parent/child module
    relationships from these dotted names so a single stub file can describe
    the sub-module tree consumed at runtime.
    """
    def __new__(cls,): ...
    def encode(self, text:str) -> list[float]:
        r"""
        Encode a single text string to a 384-dim L2-normalized vector.
        """
        ...


