# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401


def answer() -> int:
    r"""
    Wave-1 wiring probe. Returning the literal `42` lets a downstream Python
    smoke test prove that:
      1. the wrapper crate exposes the `graph` sub-module successfully, and
      2. the cross-crate `register(py, m)` indirection actually mounts a
         live callable on the resulting PyModule.
    
    Algorithm work begins in subsequent plans; this stub is the contract
    the next wave will replace. The `module = "iai_mcp_native.graph"`
    argument tells pyo3-stub-gen where to place this function in the
    generated `.pyi`.
    """
    ...

