# Top-level type stub. The actual symbols live in the embed and graph
# sub-stubs alongside this file (auto-generated by pyo3-stub-gen). This
# stub just declares the two sub-modules so `from iai_mcp_native import
# embed, graph` type-checks cleanly under `mypy --strict`.
from . import embed as embed
from . import graph as graph

__all__ = ["embed", "graph"]
